upgrade directly with a full delta if the commit chain diverges
- fix tag fetching func
- ensure booted flag is set before clearing deployments

diff --git a/dist/scripts/system-upgrade b/dist/scripts/system-upgrade
--- a/dist/scripts/system-upgrade
+++ b/dist/scripts/system-upgrade
@@ -61,6 +61,13 @@ if [ $curV != $lasV -o "$1" = force ]; then
         ## get the delta file, upgrade
         get_delta
         apply_upgrade
+        if ! $upg; then
+            # clear orphaned deltas
+            rm -f $work/*
+            get_delta last
+            apply_upgrade
+        fi
+        $upg || err "Upgrade from $curV to ${nexV}..${lasV} failed"
     fi
 fi
 
